# Generated by Django 4.2.11 on 2024-04-01 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime.now),
        ),
    ]
