# Generated by Django 4.2.11 on 2024-04-02 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0004_alter_uploadimage_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
